version: '3.4'

services:
  api-mega-sena:  
    links:  
      - sql-server 
    image: ${DOCKER_REGISTRY-}apimegasena
    build:
      context: .
      dockerfile: api-mega-sena/Dockerfile
  sql-server:
    container_name: sql-server-service
    image: microsoft/mssql-server-linux:2017-latest 
    hostname: 'sqlserver'
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "BigPassw0rd"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  
    expose:  
      - 1433
  redis:
    image: redis:alpine
    container_name: redis-service
    ports:
      - "16379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-service
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: kafka-service
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "fila_pedido:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
  flyway:
    image: boxfuse/flyway:5.2.4
    container_name: flyway-service
    command: "migrate"
    volumes:
      - ./Flyway/conf:/flyway/conf
      - ./Flyway/sql:/flyway/sql
    depends_on:
      - sql-server  